// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blockchain.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddBlockRequest struct {
	Data                 *BlockData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddBlockRequest) Reset()         { *m = AddBlockRequest{} }
func (m *AddBlockRequest) String() string { return proto.CompactTextString(m) }
func (*AddBlockRequest) ProtoMessage()    {}
func (*AddBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{0}
}

func (m *AddBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlockRequest.Unmarshal(m, b)
}
func (m *AddBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlockRequest.Marshal(b, m, deterministic)
}
func (m *AddBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlockRequest.Merge(m, src)
}
func (m *AddBlockRequest) XXX_Size() int {
	return xxx_messageInfo_AddBlockRequest.Size(m)
}
func (m *AddBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlockRequest proto.InternalMessageInfo

func (m *AddBlockRequest) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddBlockResponse struct {
	ACK                  bool     `protobuf:"varint,1,opt,name=ACK,json=aCK,proto3" json:"ACK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBlockResponse) Reset()         { *m = AddBlockResponse{} }
func (m *AddBlockResponse) String() string { return proto.CompactTextString(m) }
func (*AddBlockResponse) ProtoMessage()    {}
func (*AddBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{1}
}

func (m *AddBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBlockResponse.Unmarshal(m, b)
}
func (m *AddBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBlockResponse.Marshal(b, m, deterministic)
}
func (m *AddBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBlockResponse.Merge(m, src)
}
func (m *AddBlockResponse) XXX_Size() int {
	return xxx_messageInfo_AddBlockResponse.Size(m)
}
func (m *AddBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBlockResponse proto.InternalMessageInfo

func (m *AddBlockResponse) GetACK() bool {
	if m != nil {
		return m.ACK
	}
	return false
}

type BlockData struct {
	Timestamp            string            `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Author               string            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Identity             string            `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	ProjectID            string            `protobuf:"bytes,4,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CommitHash           string            `protobuf:"bytes,5,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	FileHashes           map[string]string `protobuf:"bytes,6,rep,name=fileHashes,proto3" json:"fileHashes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BlockData) Reset()         { *m = BlockData{} }
func (m *BlockData) String() string { return proto.CompactTextString(m) }
func (*BlockData) ProtoMessage()    {}
func (*BlockData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{2}
}

func (m *BlockData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockData.Unmarshal(m, b)
}
func (m *BlockData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockData.Marshal(b, m, deterministic)
}
func (m *BlockData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockData.Merge(m, src)
}
func (m *BlockData) XXX_Size() int {
	return xxx_messageInfo_BlockData.Size(m)
}
func (m *BlockData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockData proto.InternalMessageInfo

func (m *BlockData) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *BlockData) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BlockData) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *BlockData) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *BlockData) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *BlockData) GetFileHashes() map[string]string {
	if m != nil {
		return m.FileHashes
	}
	return nil
}

type Block struct {
	PrevBlockHash        string     `protobuf:"bytes,1,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	Data                 *BlockData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Hash                 string     `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetData() *BlockData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockchainRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainRequest) Reset()         { *m = GetBlockchainRequest{} }
func (m *GetBlockchainRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainRequest) ProtoMessage()    {}
func (*GetBlockchainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{4}
}

func (m *GetBlockchainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainRequest.Unmarshal(m, b)
}
func (m *GetBlockchainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockchainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainRequest.Merge(m, src)
}
func (m *GetBlockchainRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainRequest.Size(m)
}
func (m *GetBlockchainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainRequest proto.InternalMessageInfo

type GetBlockchainResponse struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainResponse) Reset()         { *m = GetBlockchainResponse{} }
func (m *GetBlockchainResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainResponse) ProtoMessage()    {}
func (*GetBlockchainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a884755cc01e392a, []int{5}
}

func (m *GetBlockchainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainResponse.Unmarshal(m, b)
}
func (m *GetBlockchainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockchainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainResponse.Merge(m, src)
}
func (m *GetBlockchainResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainResponse.Size(m)
}
func (m *GetBlockchainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainResponse proto.InternalMessageInfo

func (m *GetBlockchainResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*AddBlockRequest)(nil), "proto.AddBlockRequest")
	proto.RegisterType((*AddBlockResponse)(nil), "proto.AddBlockResponse")
	proto.RegisterType((*BlockData)(nil), "proto.BlockData")
	proto.RegisterMapType((map[string]string)(nil), "proto.BlockData.FileHashesEntry")
	proto.RegisterType((*Block)(nil), "proto.Block")
	proto.RegisterType((*GetBlockchainRequest)(nil), "proto.GetBlockchainRequest")
	proto.RegisterType((*GetBlockchainResponse)(nil), "proto.GetBlockchainResponse")
}

func init() { proto.RegisterFile("proto/blockchain.proto", fileDescriptor_a884755cc01e392a) }

var fileDescriptor_a884755cc01e392a = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5b, 0xab, 0xda, 0x40,
	0x10, 0x6e, 0x12, 0x13, 0x74, 0xac, 0x28, 0x83, 0x4d, 0x43, 0x2a, 0x45, 0x42, 0x1e, 0x7c, 0xb2,
	0x60, 0x1f, 0x5a, 0x0a, 0x42, 0xbd, 0xf4, 0x86, 0x7d, 0xca, 0x3f, 0x58, 0x93, 0x6d, 0x93, 0x6a,
	0x2e, 0x4d, 0x56, 0xc1, 0x9f, 0x72, 0xe0, 0xfc, 0xd8, 0x43, 0x26, 0x6b, 0xd4, 0x1c, 0x39, 0x4f,
	0xbb, 0xf3, 0x7d, 0xf3, 0xcd, 0x1d, 0xcc, 0x2c, 0x4f, 0x45, 0xfa, 0x61, 0xbb, 0x4f, 0xfd, 0x9d,
	0x1f, 0xb2, 0x28, 0x99, 0x12, 0x80, 0x3a, 0x3d, 0xce, 0x27, 0xe8, 0x2f, 0x82, 0x60, 0x59, 0xb2,
	0x1e, 0xff, 0x7f, 0xe0, 0x85, 0x40, 0x17, 0x5a, 0x01, 0x13, 0xcc, 0x52, 0xc6, 0xca, 0xa4, 0x3b,
	0x1b, 0x54, 0xfe, 0x53, 0x72, 0x59, 0x33, 0xc1, 0x3c, 0x62, 0x1d, 0x17, 0x06, 0x17, 0x61, 0x91,
	0xa5, 0x49, 0xc1, 0x71, 0x00, 0xda, 0x62, 0xb5, 0x21, 0x61, 0xdb, 0xd3, 0xd8, 0x6a, 0xe3, 0x3c,
	0xaa, 0xd0, 0xa9, 0x95, 0x38, 0x82, 0x8e, 0x88, 0x62, 0x5e, 0x08, 0x16, 0x67, 0xe4, 0xd5, 0xf1,
	0x2e, 0x00, 0x9a, 0x60, 0xb0, 0x83, 0x08, 0xd3, 0xdc, 0x52, 0x89, 0x92, 0x16, 0xda, 0xd0, 0x8e,
	0x02, 0x9e, 0x88, 0x48, 0x9c, 0x2c, 0x8d, 0x98, 0xda, 0x2e, 0x23, 0x66, 0x79, 0xfa, 0x8f, 0xfb,
	0xe2, 0xd7, 0xda, 0x6a, 0x55, 0x11, 0x6b, 0x00, 0xdf, 0x03, 0xf8, 0x69, 0x1c, 0x47, 0xe2, 0x27,
	0x2b, 0x42, 0x4b, 0x27, 0xfa, 0x0a, 0xc1, 0xaf, 0x00, 0x7f, 0xa2, 0x3d, 0x2f, 0xff, 0xbc, 0xb0,
	0x8c, 0xb1, 0x36, 0xe9, 0xce, 0xc6, 0xcd, 0x7e, 0xa7, 0xdf, 0x6b, 0x97, 0x6f, 0x89, 0xc8, 0x4f,
	0xde, 0x95, 0xc6, 0x9e, 0x43, 0xbf, 0x41, 0x97, 0x43, 0xd8, 0xf1, 0x93, 0x6c, 0xaf, 0xfc, 0xe2,
	0x10, 0xf4, 0x23, 0xdb, 0x1f, 0xb8, 0xec, 0xab, 0x32, 0xbe, 0xa8, 0x9f, 0x15, 0xe7, 0x2f, 0xe8,
	0x94, 0x07, 0x5d, 0xe8, 0x65, 0x39, 0x3f, 0x92, 0x41, 0xc5, 0x56, 0xf2, 0x5b, 0xb0, 0xde, 0x8c,
	0xfa, 0xd2, 0x66, 0x10, 0xa1, 0x15, 0x96, 0x21, 0xaa, 0x59, 0xd1, 0xdf, 0x31, 0x61, 0xf8, 0x83,
	0x8b, 0x65, 0x7d, 0x04, 0x72, 0xd7, 0xce, 0x1c, 0xde, 0x34, 0x70, 0xb9, 0x4a, 0x17, 0x0c, 0x3a,
	0x99, 0xc2, 0x52, 0x68, 0x2c, 0xaf, 0xaf, 0x93, 0x79, 0x92, 0x9b, 0x3d, 0x28, 0x00, 0x17, 0x31,
	0xce, 0xa1, 0x7d, 0xbe, 0x09, 0x34, 0xa5, 0xa0, 0x71, 0x5d, 0xf6, 0xdb, 0x67, 0x78, 0x95, 0xd1,
	0x79, 0x85, 0xbf, 0xa1, 0x77, 0x53, 0x0c, 0xbe, 0x93, 0xbe, 0xf7, 0x4a, 0xb7, 0x47, 0xf7, 0xc9,
	0x73, 0xb4, 0xad, 0x41, 0xf4, 0xc7, 0xa7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x49, 0x48, 0x72,
	0x01, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainClient is the client API for Blockchain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainClient interface {
	AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error)
	GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*AddBlockResponse, error) {
	out := new(AddBlockResponse)
	err := c.cc.Invoke(ctx, "/proto.Blockchain/AddBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBlockchain(ctx context.Context, in *GetBlockchainRequest, opts ...grpc.CallOption) (*GetBlockchainResponse, error) {
	out := new(GetBlockchainResponse)
	err := c.cc.Invoke(ctx, "/proto.Blockchain/GetBlockchain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServer is the server API for Blockchain service.
type BlockchainServer interface {
	AddBlock(context.Context, *AddBlockRequest) (*AddBlockResponse, error)
	GetBlockchain(context.Context, *GetBlockchainRequest) (*GetBlockchainResponse, error)
}

// UnimplementedBlockchainServer can be embedded to have forward compatible implementations.
type UnimplementedBlockchainServer struct {
}

func (*UnimplementedBlockchainServer) AddBlock(ctx context.Context, req *AddBlockRequest) (*AddBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlock not implemented")
}
func (*UnimplementedBlockchainServer) GetBlockchain(ctx context.Context, req *GetBlockchainRequest) (*GetBlockchainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockchain not implemented")
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Blockchain/AddBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).AddBlock(ctx, req.(*AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBlockchain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockchain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Blockchain/GetBlockchain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockchain(ctx, req.(*GetBlockchainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlock",
			Handler:    _Blockchain_AddBlock_Handler,
		},
		{
			MethodName: "GetBlockchain",
			Handler:    _Blockchain_GetBlockchain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blockchain.proto",
}
