// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sync.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FastForwardRequest struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	ConsensusMode        string   `protobuf:"bytes,2,opt,name=consensusMode,proto3" json:"consensusMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FastForwardRequest) Reset()         { *m = FastForwardRequest{} }
func (m *FastForwardRequest) String() string { return proto.CompactTextString(m) }
func (*FastForwardRequest) ProtoMessage()    {}
func (*FastForwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{0}
}

func (m *FastForwardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastForwardRequest.Unmarshal(m, b)
}
func (m *FastForwardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastForwardRequest.Marshal(b, m, deterministic)
}
func (m *FastForwardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastForwardRequest.Merge(m, src)
}
func (m *FastForwardRequest) XXX_Size() int {
	return xxx_messageInfo_FastForwardRequest.Size(m)
}
func (m *FastForwardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FastForwardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FastForwardRequest proto.InternalMessageInfo

func (m *FastForwardRequest) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *FastForwardRequest) GetConsensusMode() string {
	if m != nil {
		return m.ConsensusMode
	}
	return ""
}

type FastForwardResponse struct {
	Blocks               []*Block       `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	DivergentIndex       int64          `protobuf:"varint,2,opt,name=divergentIndex,proto3" json:"divergentIndex,omitempty"`
	CInfo                *ConsensusInfo `protobuf:"bytes,3,opt,name=cInfo,proto3" json:"cInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FastForwardResponse) Reset()         { *m = FastForwardResponse{} }
func (m *FastForwardResponse) String() string { return proto.CompactTextString(m) }
func (*FastForwardResponse) ProtoMessage()    {}
func (*FastForwardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{1}
}

func (m *FastForwardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastForwardResponse.Unmarshal(m, b)
}
func (m *FastForwardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastForwardResponse.Marshal(b, m, deterministic)
}
func (m *FastForwardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastForwardResponse.Merge(m, src)
}
func (m *FastForwardResponse) XXX_Size() int {
	return xxx_messageInfo_FastForwardResponse.Size(m)
}
func (m *FastForwardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FastForwardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FastForwardResponse proto.InternalMessageInfo

func (m *FastForwardResponse) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *FastForwardResponse) GetDivergentIndex() int64 {
	if m != nil {
		return m.DivergentIndex
	}
	return 0
}

func (m *FastForwardResponse) GetCInfo() *ConsensusInfo {
	if m != nil {
		return m.CInfo
	}
	return nil
}

type ConsensusInfo struct {
	ConsensusMode        string   `protobuf:"bytes,1,opt,name=consensusMode,proto3" json:"consensusMode,omitempty"`
	Iteration            int64    `protobuf:"varint,2,opt,name=iteration,proto3" json:"iteration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusInfo) Reset()         { *m = ConsensusInfo{} }
func (m *ConsensusInfo) String() string { return proto.CompactTextString(m) }
func (*ConsensusInfo) ProtoMessage()    {}
func (*ConsensusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{2}
}

func (m *ConsensusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusInfo.Unmarshal(m, b)
}
func (m *ConsensusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusInfo.Marshal(b, m, deterministic)
}
func (m *ConsensusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusInfo.Merge(m, src)
}
func (m *ConsensusInfo) XXX_Size() int {
	return xxx_messageInfo_ConsensusInfo.Size(m)
}
func (m *ConsensusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusInfo proto.InternalMessageInfo

func (m *ConsensusInfo) GetConsensusMode() string {
	if m != nil {
		return m.ConsensusMode
	}
	return ""
}

func (m *ConsensusInfo) GetIteration() int64 {
	if m != nil {
		return m.Iteration
	}
	return 0
}

type GetStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateRequest) Reset()         { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()    {}
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{3}
}

func (m *GetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateRequest.Unmarshal(m, b)
}
func (m *GetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateRequest.Marshal(b, m, deterministic)
}
func (m *GetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateRequest.Merge(m, src)
}
func (m *GetStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetStateRequest.Size(m)
}
func (m *GetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateRequest proto.InternalMessageInfo

type GetStateResponse struct {
	StateDebugName       string   `protobuf:"bytes,1,opt,name=stateDebugName,proto3" json:"stateDebugName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateResponse) Reset()         { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()    {}
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{4}
}

func (m *GetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateResponse.Unmarshal(m, b)
}
func (m *GetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateResponse.Marshal(b, m, deterministic)
}
func (m *GetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateResponse.Merge(m, src)
}
func (m *GetStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateResponse.Size(m)
}
func (m *GetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateResponse proto.InternalMessageInfo

func (m *GetStateResponse) GetStateDebugName() string {
	if m != nil {
		return m.StateDebugName
	}
	return ""
}

type GetNetworkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkRequest) Reset()         { *m = GetNetworkRequest{} }
func (m *GetNetworkRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkRequest) ProtoMessage()    {}
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{5}
}

func (m *GetNetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkRequest.Unmarshal(m, b)
}
func (m *GetNetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkRequest.Merge(m, src)
}
func (m *GetNetworkRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkRequest.Size(m)
}
func (m *GetNetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkRequest proto.InternalMessageInfo

type GetNetworkResponse struct {
	NodeIDs              []string `protobuf:"bytes,1,rep,name=nodeIDs,proto3" json:"nodeIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkResponse) Reset()         { *m = GetNetworkResponse{} }
func (m *GetNetworkResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkResponse) ProtoMessage()    {}
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56dcb3cab7b591a9, []int{6}
}

func (m *GetNetworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkResponse.Unmarshal(m, b)
}
func (m *GetNetworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkResponse.Merge(m, src)
}
func (m *GetNetworkResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkResponse.Size(m)
}
func (m *GetNetworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkResponse proto.InternalMessageInfo

func (m *GetNetworkResponse) GetNodeIDs() []string {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*FastForwardRequest)(nil), "proto.FastForwardRequest")
	proto.RegisterType((*FastForwardResponse)(nil), "proto.FastForwardResponse")
	proto.RegisterType((*ConsensusInfo)(nil), "proto.ConsensusInfo")
	proto.RegisterType((*GetStateRequest)(nil), "proto.GetStateRequest")
	proto.RegisterType((*GetStateResponse)(nil), "proto.GetStateResponse")
	proto.RegisterType((*GetNetworkRequest)(nil), "proto.GetNetworkRequest")
	proto.RegisterType((*GetNetworkResponse)(nil), "proto.GetNetworkResponse")
}

func init() { proto.RegisterFile("proto/sync.proto", fileDescriptor_56dcb3cab7b591a9) }

var fileDescriptor_56dcb3cab7b591a9 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x14, 0x45, 0xad, 0x08, 0xca, 0x43, 0x10, 0x06, 0x83, 0xa5, 0x71, 0x41, 0x26, 0x84, 0x10, 0x17,
	0x98, 0xe0, 0xce, 0xc4, 0x8d, 0x10, 0x08, 0x0b, 0x59, 0x94, 0x1f, 0xb0, 0xb4, 0x4f, 0x6c, 0xd0,
	0x19, 0xec, 0x0c, 0x22, 0x5f, 0xe1, 0xbf, 0xf9, 0x45, 0xa6, 0xed, 0x8c, 0xa5, 0xd0, 0x85, 0xab,
	0xb6, 0xe7, 0xde, 0xbe, 0x3b, 0xf7, 0x0d, 0x54, 0x57, 0x01, 0x97, 0xfc, 0x56, 0x6c, 0x99, 0xdb,
	0x8b, 0x5e, 0x49, 0x3e, 0x7a, 0x58, 0x8d, 0x58, 0x98, 0xbf, 0x71, 0x77, 0xe9, 0xbe, 0x3a, 0x3e,
	0x8b, 0x65, 0xfa, 0x0c, 0x64, 0xe4, 0x08, 0x39, 0xe2, 0xc1, 0xc6, 0x09, 0x3c, 0x1b, 0x3f, 0xd6,
	0x28, 0x24, 0x69, 0x43, 0x21, 0x72, 0x0a, 0xd3, 0x68, 0xe5, 0xba, 0xa5, 0xfe, 0x79, 0xec, 0xee,
	0x3d, 0x86, 0xd0, 0x56, 0x1a, 0x69, 0x43, 0xd9, 0xe5, 0x4c, 0x20, 0x13, 0x6b, 0xf1, 0xc4, 0x3d,
	0x34, 0x8f, 0x5b, 0x46, 0xb7, 0x68, 0xa7, 0x21, 0xfd, 0x36, 0xa0, 0x9e, 0x8a, 0x10, 0xab, 0x50,
	0xff, 0x67, 0x46, 0x07, 0x2a, 0x9e, 0xff, 0x89, 0xc1, 0x02, 0x99, 0x9c, 0x30, 0x0f, 0xbf, 0xa2,
	0x90, 0x9c, 0xbd, 0x47, 0xc9, 0x0d, 0xe4, 0xdd, 0x09, 0x7b, 0xe1, 0x66, 0xae, 0x65, 0x74, 0x4b,
	0xfd, 0x4b, 0x35, 0x6c, 0xa0, 0x8f, 0x12, 0x6a, 0x76, 0x6c, 0xa1, 0x33, 0x28, 0xa7, 0xf8, 0x61,
	0x11, 0x23, 0xa3, 0x08, 0xb9, 0x86, 0xa2, 0x2f, 0x31, 0x70, 0xa4, 0xcf, 0x99, 0x3a, 0x45, 0x02,
	0x68, 0x0d, 0x2e, 0xc6, 0x28, 0x67, 0xd2, 0x91, 0xa8, 0xb6, 0x48, 0xef, 0xa1, 0x9a, 0x20, 0xd5,
	0xba, 0x03, 0x15, 0x11, 0x82, 0x21, 0xce, 0xd7, 0x8b, 0xa9, 0xf3, 0xae, 0xb3, 0xf6, 0x28, 0xad,
	0x43, 0x6d, 0x8c, 0x72, 0x8a, 0x72, 0xc3, 0x83, 0xa5, 0x1e, 0xd8, 0x03, 0xb2, 0x0b, 0xd5, 0x48,
	0x13, 0x4e, 0x19, 0xf7, 0x70, 0x32, 0x8c, 0x37, 0x59, 0xb4, 0xf5, 0x67, 0xff, 0xc7, 0x80, 0x93,
	0xd9, 0x96, 0xb9, 0x64, 0x04, 0xa5, 0x9d, 0x2b, 0x20, 0x4d, 0xb5, 0x9d, 0xc3, 0x9b, 0xb7, 0xac,
	0x2c, 0x29, 0x0e, 0xa2, 0x47, 0xe4, 0x01, 0xce, 0x74, 0x23, 0xd2, 0x50, 0xce, 0xbd, 0xd6, 0xd6,
	0xd5, 0x01, 0xff, 0xfb, 0x7d, 0x00, 0x90, 0x9c, 0x9f, 0x98, 0x89, 0x31, 0xdd, 0xd3, 0x6a, 0x66,
	0x28, 0x7a, 0xc8, 0xbc, 0x10, 0x69, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x2b, 0x28,
	0x1e, 0xeb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SyncClient is the client API for Sync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncClient interface {
	FastForward(ctx context.Context, in *FastForwardRequest, opts ...grpc.CallOption) (*FastForwardResponse, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
}

type syncClient struct {
	cc *grpc.ClientConn
}

func NewSyncClient(cc *grpc.ClientConn) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) FastForward(ctx context.Context, in *FastForwardRequest, opts ...grpc.CallOption) (*FastForwardResponse, error) {
	out := new(FastForwardResponse)
	err := c.cc.Invoke(ctx, "/proto.Sync/FastForward", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/proto.Sync/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, "/proto.Sync/GetNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncServer is the server API for Sync service.
type SyncServer interface {
	FastForward(context.Context, *FastForwardRequest) (*FastForwardResponse, error)
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
}

// UnimplementedSyncServer can be embedded to have forward compatible implementations.
type UnimplementedSyncServer struct {
}

func (*UnimplementedSyncServer) FastForward(ctx context.Context, req *FastForwardRequest) (*FastForwardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FastForward not implemented")
}
func (*UnimplementedSyncServer) GetState(ctx context.Context, req *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (*UnimplementedSyncServer) GetNetwork(ctx context.Context, req *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetwork not implemented")
}

func RegisterSyncServer(s *grpc.Server, srv SyncServer) {
	s.RegisterService(&_Sync_serviceDesc, srv)
}

func _Sync_FastForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FastForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).FastForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sync/FastForward",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).FastForward(ctx, req.(*FastForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sync/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sync_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sync/GetNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sync",
	HandlerType: (*SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FastForward",
			Handler:    _Sync_FastForward_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Sync_GetState_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _Sync_GetNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sync.proto",
}
